FROM registry.cn-hangzhou.aliyuncs.com/php71-fpm/php71-fpm:v003
WORKDIR /www
RUN cp /usr/share/zoneinfo/America/Los_Angeles /etc/localtime \
&& echo 'America/Los_Angeles' >/etc/timezone

RUN mkdir -p /var/log/supervisor/



